ControlsysWSMI/Models/MonitorIntegracao.cs
namespace ControlsysWSMI
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("MONITORINTEGRACAO")]
    public partial class MonitorIntegracao
    {
        [Key]
        public int Codigo { get; set; }

        public int IntegracaoSAP { get; set; }

        public String XML { get; set; }

        public bool Integrado { get; set; }

        public DateTime DataIntegracao { get; set; }

        public DateTime DataRegistro { get; set; }
    }
}

ControlsysWSMI/Controllers/MonitorIntegracaoController.cs
using ControlsysWSMI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControlsysWSMI.Controllers
{
    public class MonitorIntegracaoController : Controller
    {
        //private Object thisLock = new Object();

        //// GET: MonitorIntegracao2
        //public ActionResult Index()
        //{            
        //    if (MontorManager.MonitorStatus)
        //    {
        //        ViewBag.Status = "Ativo";
        //    }
        //    else
        //    {
        //        ViewBag.Status = "Inativo";
        //    }

        //    return View();
        //}

        //public ActionResult IniciarMonitor()
        //{
        //    lock (thisLock)
        //    {
        //        MontorManager.MonitorStatus = true;
        //        MontorManager.Instance.Init();
        //    }

        //    if (MontorManager.MonitorStatus)
        //    {
        //        ViewBag.Status = "Ativo";
        //    }
        //    else
        //    {
        //        ViewBag.Status = "Inativo";
        //    }                        

        //    return RedirectToAction("Index");
        //}

        //public ActionResult PararMonitor()
        //{
        //    lock (thisLock)
        //    {
        //        MontorManager.MonitorStatus = false;
        //        MontorManager.Instance.Init();
        //    }

        //    if (MontorManager.MonitorStatus)
        //    {
        //        ViewBag.Status = "Ativo";
        //    }
        //    else
        //    {
        //        ViewBag.Status = "Inativo";
        //    }

        //    return RedirectToAction("Index");
        //}

        //public ActionResult StatusMonitor()
        //{   
        //    if (MontorManager.MonitorStatus)
        //    {
        //        ViewBag.Status = "Ativo";
        //    }
        //    else
        //    {
        //        ViewBag.Status = "Inativo";
        //    }

        //    return RedirectToAction("Index");
        //}
    }
}

ControlsysWSMI/Views/MonitorIntegracao/Index.cshtml
@{
   Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
        <div class="jumbotron">
            <!--<h1>Status do Monitor de Integração: @ViewBag.Status</h1>-->
            <h1>Monitor de Integração</h1>
            <h4>Ao iniciar ou reiniciar o serviço do IIS, abra o link que chama o monitor de integração, assim ativa a integração.</h4>
        </div>
        <div class="row">
            <!--
            <div class="col-md-1">                
            </div>
            <div class="col-md-11">                
                <p><a href="@Url.Action("IniciarMonitor", "MonitorIntegracao")" class="btn btn-primary btn-lg">Iniciar Integração</a></p>
            </div>
            <div class="col-md-1">
            </div>
            <div class="col-md-11">
                <p><a href="@Url.Action("PararMonitor", "MonitorIntegracao")" class="btn btn-primary btn-lg">Parar Integração</a></p>
            </div>            
             
            <div class="col-md-1">
            </div>
            <div class="col-md-11">
                <p><a href="@Url.Action("StatusMonitor", "MonitorIntegracao")" class="btn btn-primary btn-lg">Status da Integração</a></p>
            </div>-->
        </div>
    </div>
</body>
</html>